trigger:
  branches:
    include:
      - '*'
    exclude:
      - refs/pull/*/head
  paths:
    exclude:
      - docs/*
      - .github/*

# Global variables
variables:
  buildConfiguration: Release
  dotnetCoreSdk5Version: 5.0.103
  tracerHome: $(System.DefaultWorkingDirectory)/src/bin/tracer-home
  ddApiKey: $(DD_API_KEY)
  DD_DOTNET_TRACER_MSBUILD:

# Declare the datadog agent as a resource to be used as a pipeline service
resources:
  containers:
  - container: dd_agent
    image: datadog/agent
    ports:
    - 8126:8126
    env:
      DD_API_KEY: $(ddApiKey)
      DD_INSIDE_CI: true

# Stages
stages:
- stage: build
  dependsOn: []
  jobs:
  - job: build_managed
    pool:
      vmImage: windows-2019
    steps:
    - task: UseDotNet@2
      displayName: Install dotnet core sdk 5.0
      inputs:
        packageType: sdk
        version: $(dotnetCoreSdk5Version)

    - task: MSBuild@1
      displayName: Build all managed projects
      inputs:
        solution: Datadog.Trace.proj
        configuration: $(buildConfiguration)
        msbuildArguments: /t:BuildCsharp
        maximumCpuCount: true

    - task: MSBuild@1
      displayName: Publish managed profiler to tracer home for Windows and Linux builds
      inputs:
        solution: Datadog.Trace.proj
        configuration: $(buildConfiguration)
        msbuildArguments: /t:PublishManagedProfilerOnDisk
        maximumCpuCount: true

    - task: DotNetCoreCLI@2
      displayName: Create NuGet packages
      inputs:
        command: pack
        nobuild: true
        packagesToPack: src/Datadog.Trace/Datadog.Trace.csproj;src/Datadog.Trace.OpenTracing/Datadog.Trace.OpenTracing.csproj
        packDirectory: $(System.DefaultWorkingDirectory)/nuget-output
        configuration: $(buildConfiguration)

    - publish: $(System.DefaultWorkingDirectory)/nuget-output
      displayName: Upload NuGet packages
      artifact: nuget-packages

    - publish: $(System.DefaultWorkingDirectory)
      displayName: Upload working directory after the managed build
      artifact: build-managed

  - job: build_native_windows
    dependsOn: build_managed # The native build relies on Datadog.Trace.ClrProfiler.Managed.Loader to be built
    pool:
      vmImage: windows-2019
    variables:
      msiHome: $(System.DefaultWorkingDirectory)/src/WindowsInstaller/bin/$(buildConfiguration)
    steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: build-managed
        path: $(System.DefaultWorkingDirectory)

    - task: UseDotNet@2
      displayName: install dotnet core sdk 5.0
      inputs:
        packageType: sdk
        version: $(dotnetCoreSdk5Version)

    # This is only here because the msi build later causes a restore error...not sure why
    - task: DotNetCoreCLI@2
      displayName: dotnet restore
      inputs:
        command: restore
        projects: src/**/*.csproj

    - task: NuGetToolInstaller@1
      displayName: install nuget

    - task: NuGetCommand@2
      displayName: nuget restore
      inputs:
        restoreSolution: Datadog.Trace.Native.sln
        verbosityRestore: Normal

    # this triggers a dependency chain that builds all the managed, x64, and x86 dlls, and the zip and msi files
    # Outputs include:
    # - Windows Datadog.Trace.ClrProfiler.Native.dll (x86 and x64)
    # - Windows MSI (x86 and x64)
    # - Windows tracer home directory
    - task: MSBuild@1
      displayName: build both msi
      inputs:
        solution: Datadog.Trace.proj
        configuration: $(buildConfiguration)
        msbuildArguments: /t:msi /p:Platform=All;ZipHomeDirectory=true;RunWixToolsOutOfProc=true
        maximumCpuCount: true

    - publish: $(System.DefaultWorkingDirectory)
      displayName: Upload repo after windows build
      artifact: build-repo-managed-native-windows

    - publish: $(tracerHome)/win-x86
      displayName: Upload Windows x86 profiler directory
      artifact: build-profiler-windows-x86

    - publish: $(tracerHome)/win-x64
      displayName: Upload Windows x64 profiler directory
      artifact: build-profiler-windows-x64

    - publish: $(msiHome)/x86/en-us
      displayName: Upload Windows x86 MSI
      artifact: windows-msi-x86

    - publish: $(msiHome)/x64/en-us
      displayName: Upload Windows x64 MSI
      artifact: windows-msi-x64

    - publish: $(tracerHome).zip
      displayName: Upload Windows tracer home zip
      artifact: windows-tracer-home

  - job: build_native_linux
    dependsOn: build_managed # The native build relies on Datadog.Trace.ClrProfiler.Managed.Loader to be built
    pool:
      vmImage: ubuntu-20.04
    steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: build-managed
        path: $(System.DefaultWorkingDirectory)

    - script: |
        chmod +x $(System.DefaultWorkingDirectory)/build/docker/Datadog.Trace.ClrProfiler.Native.sh
      displayName: 'Workaround: Restore wiped executable permission on build/docker/Datadog.Trace.ClrProfiler.Native.sh'

    - task: DockerCompose@0
      displayName: docker-compose run Profiler
      inputs:
        containerregistrytype: Container Registry
        dockerComposeCommand: run Profiler

    - script: |
        chmod +x $(System.DefaultWorkingDirectory)/build/docker/package.sh
      displayName: 'Workaround: Restore wiped executable permission on build/docker/package.sh'

    - task: DockerCompose@0
      displayName: docker-compose run package
      inputs:
        containerregistrytype: Container Registry
        dockerComposeCommand: run package

    - publish: $(System.DefaultWorkingDirectory)/src/Datadog.Trace.ClrProfiler.Native/bin/Release/x64
      displayName: Uploading linux tracer home artifact
      artifact: build-linux-tracer-home

    - publish: $(System.DefaultWorkingDirectory)/deploy/linux
      displayName: Publish Linux packages
      artifact: linux-packages

  - job: build_native_alpine_linux
    dependsOn: build_managed # The native build relies on Datadog.Trace.ClrProfiler.Managed.Loader to be built
    pool:
      vmImage: ubuntu-20.04
    steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: build-managed
        path: $(System.DefaultWorkingDirectory)

    - script: |
        chmod +x $(System.DefaultWorkingDirectory)/build/docker/Datadog.Trace.ClrProfiler.Native.sh
      displayName: 'Workaround: Restore wiped executable permission on build/docker/Datadog.Trace.ClrProfiler.Native.sh'

    - task: DockerCompose@0
      displayName: docker-compose run Profiler.Alpine
      inputs:
        containerregistrytype: Container Registry
        dockerComposeCommand: run Profiler.Alpine

    - script: |
        chmod +x $(System.DefaultWorkingDirectory)/build/docker/package.sh
      displayName: 'Workaround: Restore wiped executable permission on build/docker/package.sh'

    - task: DockerCompose@0
      displayName: docker-compose run package.alpine
      inputs:
        containerregistrytype: Container Registry
        dockerComposeCommand: run package.alpine

    - publish: $(System.DefaultWorkingDirectory)/src/Datadog.Trace.ClrProfiler.Native/bin/Release/x64
      displayName: Uploading alpine linux tracer home artifact
      artifact: build-alpine-linux-tracer-home

    - publish: $(System.DefaultWorkingDirectory)/deploy/linux
      displayName: Publish Alpine Linux package
      artifact: linux-alpine-packages

- stage: unit_tests
  dependsOn: build
  jobs:
  - job: unit_tests_managed
    strategy:
      matrix:
        windows:
          imageName: windows-2019
        linux:
          imageName: ubuntu-18.04
        macos:
          imageName: macOS-10.15
    pool:
      vmImage: $(imageName)
    steps:

    - checkout: none

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: build-managed
        path: $(System.DefaultWorkingDirectory)

    - template: steps/install-dotnet.yml

    # Ideally we would use the following MSBuild command which can more intelligently parallelize the build
    #    - task: MSBuild@1
    #      displayName: Build all managed unit test projects
    #      inputs:
    #        solution: Datadog.Trace.proj
    #        configuration: $(buildConfiguration)
    #        msbuildArguments: /t:BuildCsharpTests
    #        maximumCpuCount: true

    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: build
        configuration: $(buildConfiguration)
        arguments: /nowarn:netsdk1138
        projects: |
          test/**/*.Tests.csproj
      env:
        DD_SERVICE: dd-trace-dotnet

    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: test
        arguments: '--no-build'
        configuration: $(buildConfiguration)
        projects: test/**/*.Tests.csproj
      env:
        DD_SERVICE: dd-trace-dotnet

  - job: unit_tests_managed_linux_arm64
    pool: Arm64
    workspace:
      clean: all

    steps:

    - checkout: none

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: build-managed
        path: $(System.DefaultWorkingDirectory)

    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: test
        configuration: $(buildConfiguration)
        projects: test/**/*.Tests.csproj
      env:
        DD_SERVICE: dd-trace-dotnet

  - job: native_unit_tests_windows
    pool:
      vmImage: windows-2019

    steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: build-repo-managed-native-windows
        path: $(System.DefaultWorkingDirectory)

    # Install the .NET SDK so any managed libraries needed for the C++ unit tests can be built
    - template: steps/install-dotnet.yml

    # This should already be accounted for but unfortunately it is not
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: build
        configuration: $(buildConfiguration)
        arguments: /nowarn:netsdk1138
        projects: |
          test/**/Samples.ExampleLibrary*.csproj

    - task: MSBuild@1
      displayName: Build x86 native unit test projects
      inputs:
        solution: Datadog.Trace.proj
        platform: x86
        configuration: $(buildConfiguration)
        msbuildArguments: /t:BuildCppTests
        maximumCpuCount: true

    - task: MSBuild@1
      displayName: Build x64 native unit test projects
      inputs:
        solution: Datadog.Trace.proj
        platform: x64
        configuration: $(buildConfiguration)
        msbuildArguments: /t:BuildCppTests
        maximumCpuCount: true

    - script: Datadog.Trace.ClrProfiler.Native.Tests.exe --gtest_output=xml
      displayName: run tests
      workingDirectory: $(System.DefaultWorkingDirectory)/test/Datadog.Trace.ClrProfiler.Native.Tests/bin/$(buildConfiguration)/x86

    - script: Datadog.Trace.ClrProfiler.Native.Tests.exe --gtest_output=xml
      displayName: run tests
      workingDirectory: $(System.DefaultWorkingDirectory)/test/Datadog.Trace.ClrProfiler.Native.Tests/bin/$(buildConfiguration)/x64
      condition: succeededOrFailed()

    - task: PublishTestResults@2
      displayName: publish test results
      inputs:
        testResultsFiles: test/**/test*.xml
      condition: succeededOrFailed()

- stage: benchmarks
  dependsOn: build
  condition: true
  jobs:

  #### Windows 

  - job: Windows
    pool: Benchmarks
    
    workspace:
      clean: all

    # Enable the Datadog Agent service for this job
    services:
      dd_agent: dd_agent
    variables:
      tracerHomeName: windows-tracer-home
      tracerHome: $(System.DefaultWorkingDirectory)/src/bin/$(tracerHomeName)
      msiHome: $(System.DefaultWorkingDirectory)/src/bin/msi
      nuget_packages: $(Pipeline.Workspace)/.nuget/packages

    steps:

    - checkout: none

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: build-managed
        path: $(System.DefaultWorkingDirectory)

    - task: UseDotNet@2
      displayName: Install dotnet core sdk 5.0
      inputs:
        packageType: sdk
        version: $(dotnetCoreSdk5Version)

    - task: DotNetCoreCLI@2
      displayName: dotnet restore
      inputs:
        command: restore
        projects: src/**/*.csproj

    - task: DotNetCoreCLI@2
      displayName: Benchmarks
      inputs:
        command: 'run'
        projects: '$(System.DefaultWorkingDirectory)/test/benchmarks/Benchmarks.Trace/Benchmarks.Trace.csproj'
        arguments: '-c Release -f netcoreapp3.1 -- -r net472 netcoreapp3.1 -m -f * --iterationTime 2000'
      env:
        DD_ENV: CI
        DD_SERVICE: dd-trace-dotnet

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Start-Sleep -s 120'